# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master, android-target ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}

    steps:
    - name: Setup Java 8 for sdkmanager
      uses: actions/setup-java@v1
      with:
        java-version: '8'
        java-package: jdk
        architecture: x64
    - name: Download ndk
      run: $ANDROID_HOME/tools/bin/sdkmanager 'ndk;21.2.6472646' # TODO read from some config file
    - name: Setup Java environment based on setup-java
      uses: actions/setup-java@v1
      with:
        java-version: '11'
        java-package: jdk
        architecture: x64
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # build cache
    - name: Cache
      uses: actions/cache@v1.1.2
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
      # An ordered list of keys to use for restoring the cache if no cache hit occurred for key
        restore-keys: |
          ${{ runner.os }}-gradle-
    - uses: actions/cache@v1.1.2
      with:
        path: ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
    - uses: actions/cache@v1.1.2
      with:
        path: ~/.konan
        key: ${{ runner.os }}-konan
    # Runs a single command using the runners shell
    - name: build and test
      run: ./gradlew allTests
    - name: run spotless
      run: ./gradlew spotlessCheck
    - name: build dist
      run: ./gradlew buildOnServer
    - name: Upload test results for sqlitebindings
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: sqlitebindings-test-reports
        path: sqlitebindings/build/reports
    - name: Upload test results for ksqlite3
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: ksqlite3-test-reports
        path: ksqlite3/build/reports
    - name: Upload JNI failures
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: ksqlite3-jni-errors
        path: ksqlite3/hs_err*
    - name: Upload Dist
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.os }}-dist
        path: build/dist
  androidTests:
    needs: build
    runs-on: macosx-latest
    strategy:
      matrix:
        api-level: [21, 24, 27, 29]
    steps:
    - name: Setup Java environment based on setup-java
      uses: actions/setup-java@v1
      with:
        java-version: '11'
        java-package: jdk
        architecture: x64
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # build cache
    - name: Cache
      uses: actions/cache@v1.1.2
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
      # An ordered list of keys to use for restoring the cache if no cache hit occurred for key
        restore-keys: |
          ${{ runner.os }}-gradle-
    - uses: actions/cache@v1.1.2
      with:
        path: ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
    - uses: actions/cache@v1.1.2
      with:
        path: ~/.konan
        key: ${{ runner.os }}-konan
    - name: Run Integration Tests - x86
      uses: ReactiveCircus/android-emulator-runner@v2.9.0
      with:
        api-level: ${{ matrix.api-level }}
        arch: x86
        script: ./gradlew connectedCheck --stacktrace
    - name: Run Integration Tests - x86_64
      uses: ReactiveCircus/android-emulator-runner@v2.9.0
      with:
        api-level: ${{ matrix.api-level }}
        arch: x86_64
        script: ./gradlew connectedCheck --stacktrace
    - name: Upload build reports
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: android test results
        path: ./**/build/reports
  buildFinalArtifacts:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Setup Java environment based on setup-java
        uses: actions/setup-java@v1
        with:
          java-version: '11'
          java-package: jdk
          architecture: x64
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # build cache
      - name: Cache
        uses: actions/cache@v1.1.2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          # An ordered list of keys to use for restoring the cache if no cache hit occurred for key
          restore-keys: |
            ${{ runner.os }}-gradle-
      - uses: actions/cache@v1.1.2
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
      - uses: actions/cache@v1.1.2
        with:
          path: ~/.konan
          key: ${{ runner.os }}-konan
      # download artifacts
      # ubuntu-latest, macos-latest, windows-latest -> should match the strategies of build
      - name: Download linux dist
        uses: actions/download-artifact@v2
        with:
          name: ubuntu-latest-dist
          path: artifacts/linux
      - name: Download mac dist
        uses: actions/download-artifact@v2
        with:
          name: macos-latest-dist
          path: artifacts/mac 
      - name: Download windows dist
        uses: actions/download-artifact@v2
        with:
          name: windows-latest-dist
          path: artifacts/windows
      - name: test and publish
        run: DIST_OUTPUTS=artifacts ./gradlew jvmTest createCombinedRepo
      - name: Upload Repo
        uses: actions/upload-artifact@v2
        with:
          name: combined-repo
          path: build/dist/combinedRepo
