# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Setup Java environment based on AdoptOpenJDK
      uses: joschi/setup-jdk@v1.1.2
      with:
        # OpenJDK version, example: "openjdk8", "openjdk11", "openjdk13".
        java-version: 'openjdk11' 
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # build cache
    - name: Cache
      uses: actions/cache@v1.1.2
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
      # An ordered list of keys to use for restoring the cache if no cache hit occurred for key
        restore-keys: |
          ${{ runner.os }}-gradle-
    - uses: actions/cache@v1.1.2
      with:
        path: ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
    - uses: actions/cache@v1.1.2
      with:
        path: ~/.konan
        key: ${{ runner.os }}-konan
    # Runs a single command using the runners shell
    - name: build and test
      run: ./gradlew allTests
    - name: run spotless
      run: ./gradlew spotlessCheck
    - name: Upload test results for sqlitebindings
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: sqlitebindings-test-reports
        path: sqlitebindings/build/reports
    - name: Upload test results for ksqlite3
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: ksqlite3-test-reports
        path: ksqlite3/build/reports
    - name: Upload JNI failures
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: ksqlite3-jni-errors
        path: ksqlite3/hs_err*
